# Generated by Django 4.1 on 2023-06-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Apartamento",
            fields=[
                ("categoria", models.CharField(max_length=200)),
                ("precoDia", models.FloatField()),
                ("capacidade", models.IntegerField()),
                ("codigo", models.IntegerField(primary_key=True, serialize=False)),
                ("imagem1", models.ImageField(upload_to="")),
                ("imagem2", models.ImageField(upload_to="")),
                ("imagem3", models.ImageField(upload_to="")),
                ("imagem4", models.ImageField(upload_to="")),
            ],
        ),
    ]
