# Generated by Django 4.1 on 2023-06-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitereserva", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apartamento",
            name="codigo",
        ),
        migrations.AddField(
            model_name="apartamento",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=0,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
