# Generated by Django 4.1.5 on 2023-01-17 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animal",
            name="habitatpk",
        ),
        migrations.AddField(
            model_name="animal",
            name="habitat",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="animals.habitat",
            ),
        ),
    ]
