# Generated by Django 4.1.5 on 2023-01-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0002_remove_animal_habitatpk_animal_habitat"),
    ]

    operations = [
        migrations.AddField(
            model_name="habitat",
            name="description",
            field=models.CharField(
                default="Nenhuma descrição foi adicionada", max_length=1000
            ),
        ),
    ]
