# Generated by Django 4.1.5 on 2023-01-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0005_alter_animal_animal_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="A_description",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
