# Generated by Django 4.1.5 on 2023-01-20 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0006_animal_a_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="animal",
            old_name="A_description",
            new_name="Animal_description",
        ),
    ]
